export const INITIAL_AGENTS = [
  {
    id: "agent-001",
    name: "Javohir Karimov",
    phone: "+998 90 111 22 33",
    email: "javohir@example.com",
    region: "Toshkent shahri",
    route: "Yunusobod - Mirzo Ulug'bek",
    status: "ACTIVE",
    targetAmount: 30000000,
    commissionPercent: 3,
    cashBalance: 2500000,
    customerIds: [],
    orderIds: [],
    paymentIds: [],
    vehicleId: null,
    warehouseId: null,
    salesAmount: 0,
    collectedAmount: 0,
    debtAmount: 0,
    commissionAmount: 0,
    lastVisitAt: null,
    lastOrderAt: null,
    lastPaymentAt: null,
    note: "Asosiy savdo agenti.",
    createdAt: "2026-08-12T10:00:00.000Z",
    updatedAt: "2026-08-12T10:00:00.000Z",
  },
  {
    id: "agent-002",
    name: "Azizbek Olimov",
    phone: "+998 93 444 55 66",
    email: "",
    region: "Toshkent viloyati",
    route: "Chirchiq - Qibray",
    status: "ACTIVE",
    targetAmount: 20000000,
    commissionPercent: 2.5,
    cashBalance: 1200000,
    customerIds: [],
    orderIds: [],
    paymentIds: [],
    vehicleId: null,
    warehouseId: null,
    salesAmount: 0,
    collectedAmount: 0,
    debtAmount: 0,
    commissionAmount: 0,
    lastVisitAt: null,
    lastOrderAt: null,
    lastPaymentAt: null,
    note: "",
    createdAt: "2026-08-12T10:30:00.000Z",
    updatedAt: "2026-08-12T10:30:00.000Z",
  },
];

export const agentsMock = INITIAL_AGENTS;
