export const WAREHOUSES = [
    {
        id: "wh-main",
        name: "Asosiy ombor",
        branch: "Asosiy filial",
    },
    {
        id: "wh-production",
        name: "Ishlab chiqarish ombori",
        branch: "Asosiy filial",
    },
    {
        id: "wh-finished",
        name: "Tayyor mahsulot ombori",
        branch: "Asosiy filial",
    },
];

export const INITIAL_WAREHOUSE_STOCK = [
    {
        id: "stock-001",
        warehouseId: "wh-main",
        productId: "prd-001",
        productName: "Un Premium",
        sku: "4821",
        type: "RAW_MATERIAL",
        category: "Xomashyo",
        unit: "kg",
        quantity: 860,
        reserved: 40,
        minimumStock: 200,
        cost: 4200,
    },
    {
        id: "stock-002",
        warehouseId: "wh-main",
        productId: "prd-002",
        productName: "Shakar",
        sku: "7314",
        type: "RAW_MATERIAL",
        category: "Xomashyo",
        unit: "kg",
        quantity: 145,
        reserved: 20,
        minimumStock: 200,
        cost: 13500,
    },
    {
        id: "stock-003",
        warehouseId: "wh-main",
        productId: "prd-003",
        productName: "Vanilin",
        sku: "2059",
        type: "RAW_MATERIAL",
        category: "Qo‘shimchalar",
        unit: "kg",
        quantity: 0,
        reserved: 0,
        minimumStock: 5,
        cost: 78000,
    },
    {
        id: "stock-004",
        warehouseId: "wh-finished",
        productId: "prd-004",
        productName: "Shokoladli pechenye",
        sku: "9942",
        type: "FINISHED_GOOD",
        category: "Pechenye",
        unit: "dona",
        quantity: 1240,
        reserved: 120,
        minimumStock: 300,
        cost: 3150,
    },
    {
        id: "stock-005",
        warehouseId: "wh-finished",
        productId: "prd-005",
        productName: "Klassik pechenye",
        sku: "6148",
        type: "FINISHED_GOOD",
        category: "Pechenye",
        unit: "dona",
        quantity: 410,
        reserved: 30,
        minimumStock: 300,
        cost: 2800,
    },
];