export const INITIAL_SUPPLIERS = [
    {
        id: "sup-001",
        name: "Oltin Don Trade",
        companyName: "Oltin Don Trade MChJ",
        phone: "+998 90 123 45 67",
        email: "info@oltindon.uz",
        address: "Toshkent shahri",
        contactPerson: "Javlon Karimov",
        category: "Xomashyo",
        status: "ACTIVE",
        note: "Asosiy un yetkazib beruvchi.",
        createdAt: "01.08.2026 10:00",
    },
    {
        id: "sup-002",
        name: "Samarqand Sugar",
        companyName: "Samarqand Sugar MChJ",
        phone: "+998 93 555 21 21",
        email: "sales@sugar.uz",
        address: "Samarqand shahri",
        contactPerson: "Aziz Normurodov",
        category: "Xomashyo",
        status: "ACTIVE",
        note: "",
        createdAt: "02.08.2026 11:30",
    },
    {
        id: "sup-003",
        name: "Packaging Pro",
        companyName: "Packaging Pro",
        phone: "+998 95 777 44 55",
        email: "",
        address: "Toshkent viloyati",
        contactPerson: "Dilshod",
        category: "Qadoqlash",
        status: "ACTIVE",
        note: "",
        createdAt: "05.08.2026 09:20",
    },
];