export const productsMock = [
  {
    id: "prd-001",
    name: "Un Premium",
    sku: "RM-0001",
    barcode: "4780012345011",
    type: "RAW_MATERIAL",
    category: "Xomashyo",
    brand: "Premium Mill",
    unit: "kg",
    stock: 860,
    minimumStock: 200,
    cost: 4200,
    salePrice: null,
    supplierId: "sup-001",
    supplierName: "Oltin Don Trade",
    tax: 12,
    discount: 0,
    image: "",
    notes: "Asosiy un xomashyosi.",
    status: "ACTIVE",
  },
  {
    id: "prd-002",
    name: "Shakar",
    sku: "RM-0002",
    barcode: "4780012345028",
    type: "RAW_MATERIAL",
    category: "Xomashyo",
    brand: "Sweet Line",
    unit: "kg",
    stock: 145,
    minimumStock: 200,
    cost: 13500,
    salePrice: null,
    supplierId: "sup-002",
    supplierName: "Samarqand Sugar",
    tax: 12,
    discount: 0,
    image: "",
    notes: "",
    status: "ACTIVE",
  },
  {
    id: "prd-003",
    name: "Vanilin",
    sku: "RM-0003",
    barcode: "4780012345035",
    type: "RAW_MATERIAL",
    category: "Qo'shimchalar",
    brand: "Aroma Food",
    unit: "kg",
    stock: 0,
    minimumStock: 5,
    cost: 78000,
    salePrice: null,
    supplierId: "sup-003",
    supplierName: "Aroma Import",
    tax: 12,
    discount: 0,
    image: "",
    notes: "",
    status: "ACTIVE",
  },
  {
    id: "prd-004",
    name: "Shokoladli pechenye",
    sku: "FG-0001",
    barcode: "4780012345042",
    type: "FINISHED_GOOD",
    category: "Pechenye",
    brand: "Universal Foods",
    unit: "dona",
    stock: 1240,
    minimumStock: 300,
    cost: 3150,
    salePrice: 5500,
    supplierId: null,
    supplierName: null,
    tax: 12,
    discount: 5,
    image: "",
    notes: "Asosiy tayyor mahsulotlardan biri.",
    status: "ACTIVE",
  },
  {
    id: "prd-005",
    name: "Klassik pechenye",
    sku: "FG-0002",
    barcode: "4780012345059",
    type: "FINISHED_GOOD",
    category: "Pechenye",
    brand: "Universal Foods",
    unit: "dona",
    stock: 410,
    minimumStock: 300,
    cost: 2800,
    salePrice: 4900,
    supplierId: null,
    supplierName: null,
    tax: 12,
    discount: 0,
    image: "",
    notes: "",
    status: "ACTIVE",
  },
  {
    id: "prd-006",
    name: "Qadoqlash qutisi",
    sku: "RM-0004",
    barcode: "4780012345066",
    type: "RAW_MATERIAL",
    category: "Qadoqlash",
    brand: "Pack House",
    unit: "dona",
    stock: 80,
    minimumStock: 150,
    cost: 1200,
    salePrice: null,
    supplierId: "sup-004",
    supplierName: "Pack House",
    tax: 12,
    discount: 0,
    image: "",
    notes: "",
    status: "ACTIVE",
  },
  {
    id: "prd-007",
    name: "Sinov mahsuloti",
    sku: "TR-0001",
    barcode: "4780012345073",
    type: "TRADING_PRODUCT",
    category: "Boshqa",
    brand: "Brendsiz",
    unit: "dona",
    stock: 20,
    minimumStock: 10,
    cost: 10000,
    salePrice: 14500,
    supplierId: "sup-005",
    supplierName: "Sinov yetkazib beruvchisi",
    tax: 12,
    discount: 0,
    image: "",
    notes: "",
    status: "INACTIVE",
  },
];
