export const navigationItems = [
    {
        id: "dashboard",
        label: "Bosh sahifa",
        path: "/dashboard",
        icon: "LayoutDashboard",
        module: "dashboard",
    },
    {
        id: "sales",
        label: "Savdo",
        path: "/sales/terminal",
        icon: "ShoppingCart",
        module: "sales",
    },
    {
        id: "manufacturing",
        label: "Ishlab chiqarish",
        path: "/manufacturing",
        icon: "Factory",
        module: "manufacturing",
    },
    {
        id: "warehouse",
        label: "Ombor",
        path: "/warehouse",
        icon: "Warehouse",
        module: "warehouse",
    },
    {
        id: "purchases",
        label: "Xaridlar",
        path: "/purchases",
        icon: "PackagePlus",
        module: "purchases",
    },
    {
        id: "products",
        label: "Mahsulotlar",
        path: "/products",
        icon: "Package",
        module: "products",
    },
    {
        id: "customers",
        label: "Mijozlar",
        path: "/customers",
        icon: "Users",
        module: "customers",
    },
    {
        id: "agents",
        label: "Agentlar",
        path: "/agents",
        icon: "Users",
        module: "agents",
    },
    {
        id: "suppliers",
        label: "Yetkazib beruvchilar",
        path: "/suppliers",
        icon: "Truck",
        module: "suppliers",
    },
    {
        id: "finance",
        label: "Moliya",
        path: "/finance",
        icon: "WalletCards",
        module: "finance",
    },
    {
        id: "employees",
        label: "Xodimlar",
        path: "/hr",
        icon: "UserRoundCog",
        module: "employees",
    },
    {
        id: "reports",
        label: "Hisobotlar",
        path: "/reports",
        icon: "ChartNoAxesCombined",
        module: "reports",
    },
    {
        id: "settings",
        label: "Sozlamalar",
        path: "/settings",
        icon: "Settings",
    },
];
