export const customerAgentTajikOverrides = {
  "Agent": "Агент",
  "Agent ma'lumotlari": "Маълумоти агент",
  "Agent nomini kiriting.": "Номи агентро ворид кунед.",
  "Agent tafsiloti": "Тафсилоти агент",
  "Agent tanlanmagan": "Агент интихоб нашудааст",
  "Agent xizmat ko'rsatadigan mijozlar.": "Мизоҷоне, ки агент хизмат мерасонад.",
  "Agentlarga qaytish": "Бозгашт ба агентҳо",
  "Amallar": "Амалҳо",
  "Bajarildi": "Иҷро шуд",
  "Bajarilgan": "Иҷрошуда",
  "Bank": "Бонк",
  "Barcha agentlar": "Ҳамаи агентҳо",
  "Barcha regionlar": "Ҳамаи минтақаҳо",
  "Barcha segmentlar": "Ҳамаи сегментҳо",
  "Barcha statuslar": "Ҳамаи ҳолатҳо",
  "Barcha turlar": "Ҳамаи навъҳо",
  "Bekor": "Бекор",
  "Bekor qilingan": "Бекоршуда",
  "Bekor qilish": "Бекор кардан",
  "Biriktirilgan mijozlar": "Мизоҷони пайвастшуда",
  "Biriktirish": "Пайваст кардан",
  "Boshqa": "Дигар",
  "Brauzer xotirasidagi CRM": "CRM дар хотираи браузер",
  "Bu telefon raqam bilan mijoz mavjud.": "Бо ин рақам мизоҷ мавҷуд аст.",
  "Buyurtma": "Фармоиш",
  "Buyurtmalar": "Фармоишҳо",
  "Customer created": "Мизоҷ сохта шуд",
  "Doimiy": "Доимӣ",
  "Email formati noto'g'ri.": "Формати почтаи электронӣ нодуруст аст.",
  "Eng faol 5 mijoz": "5 мизоҷи фаъолтарин",
  "Faol": "Фаъол",
  "Faol emas": "Ғайрифаъол",
  "Faol/Faol emas": "Фаъол/Ғайрифаъол",
  "Holat": "Ҳолат",
  "Hudud": "Ҳудуд",
  "Hududni kiriting.": "Ҳудудро ворид кунед.",
  "Ism yoki mijoz nomi majburiy.": "Ном ё номи мизоҷ ҳатмист.",
  "Izoh": "Шарҳ",
  "Jami": "Ҳамагӣ",
  "Jismoniy shaxs": "Шахси воқеӣ",
  "Karta": "Корт",
  "Keyingi aloqa": "Пайгирӣ",
  "Keyingi aloqa yoki izoh mavjud emas.": "Пайгирӣ ё шарҳ мавҷуд нест.",
  "Ko'rish": "Дидан",
  "Komissiya": "Комиссия",
  "Komissiyani tekshiring.": "Комиссияро санҷед.",
  "Kompaniya": "Ширкат",
  "Kredit limiti manfiy bo'lmasin.": "Лимити қарз манфӣ набошад.",
  "Limitdan oshgan": "Аз лимит гузаштааст",
  "Ma'lumot yo'q": "Маълумот нест",
  "Manba": "Манбаъ",
  "Marshrut": "Масир",
  "Mijoz": "Мизоҷ",
  "Mijoz biriktirish": "Пайваст кардани мизоҷ",
  "Mijozlar": "Мизоҷон",
  "Mijozlarga qaytish": "Бозгашт ба мизоҷон",
  "Moliya moduli bilan agent tushumlari shu kelishuv orqali ulanadi.": "Даромадҳои агент аз модули молия ҳамин ҷо пайваст мешаванд.",
  "Naqd": "Нақд",
  "O'chirish": "Нест кардан",
  "O'chirish xavfsizligi:": "Бехатарии несткунӣ:",
  "Ochiq": "Кушода",
  "Ortga": "Бозгашт",
  "Oxirgi savdo": "Фурӯши охирин",
  "Performance": "Натиҷа",
  "Qarz": "Қарз",
  "Qarz holati": "Ҳолати қарз",
  "Qarzdor": "Қарздор",
  "Qarzsiz": "Бе қарз",
  "Qo'ng'iroq": "Занг",
  "Qo'shish": "Илова кардан",
  "QR": "QR",
  "Real sales": "Фурӯши воқеӣ",
  "Real sales orderlar asosida reja bajarilishi.": "Иҷрои нақша аз рӯи фармоишҳои воқеии фурӯш.",
  "Reja": "Нақша",
  "Reja manfiy bo'lishi mumkin emas.": "Нақша манфӣ буда наметавонад.",
  "Riskli": "Хавфнок",
  "Sana": "Сана",
  "Saqlash": "Сабт кардан",
  "Savdo": "Фурӯш",
  "Savdo agentining asosiy ma'lumotlari.": "Маълумоти асосии агенти фурӯш.",
  "Savdo moduli bilan agent buyurtmalari shu kelishuv orqali ulanadi.": "Фармоишҳои агент аз модули фурӯш ҳамин ҷо пайваст мешаванд.",
  "Savdo raqami": "Рақами фурӯш",
  "Segment": "Сегмент",
  "Segment:": "Сегмент:",
  "so'm": "сум",
  "Summa": "Маблағ",
  "ta": "адад",
  "ta natija": "натиҷа",
  "Tahrirlash": "Таҳрир",
  "Takror telefon:": "Телефони такрорӣ:",
  "Telefon": "Телефон",
  "Telefon majburiy.": "Телефон ҳатмист.",
  "Telefon raqamini kiriting.": "Рақами телефонро ворид кунед.",
  "To'langan": "Пардохтшуда",
  "To'lov": "Пардохт",
  "To'lov muddati manfiy bo'lmasin.": "Муҳлати пардохт манфӣ набошад.",
  "To'lov qabul qilish": "Қабули пардохт",
  "To'lov turi": "Навъи пардохт",
  "To'lovlar": "Пардохтҳо",
  "Turi": "Навъ",
  "Uchrashuv": "Вохӯрӣ",
  "Usul": "Усул",
  "VIP": "VIP",
  "Yangi": "Нав",
  "Yangi savdo": "Фурӯши нав",
  "Agent bilan bog'lanish uchun asosiy ma'lumotlar.": "Маълумоти асосӣ барои тамос бо агент.",
  "Agent F.I.Sh.": "Ному насаби агент",
  "Agent faol": "Агент фаъол",
  "Agent haqida qo'shimcha ma'lumot...": "Маълумоти иловагӣ дар бораи агент...",
  "Agent topilmadi": "Агент ёфт нашуд",
  "Agent yaratish": "Сохтани агент",
  "Agent, telefon, hudud yoki marshrut...": "Агент, телефон, ҳудуд ё масир...",
  "Agentdagi naqd pul (manual)": "Пули нақди агент (дастӣ)",
  "Agentdagi pul": "Пули назди агент",
  "Agentdan ajratish": "Ҷудо кардан аз агент",
  "Agentlar topilmadi.": "Агентҳо ёфт нашуданд.",
  "Agentlardagi pul": "Пули назди агентҳо",
  "Agentni o'chirib bo'lmaydi": "Агентро нест кардан мумкин нест",
  "Agentni o'chirish": "Нест кардани агент",
  "Agentni o'zgartirish": "Иваз кардани агент",
  "Agentni tahrirlash": "Таҳрири агент",
  "Aloqa uchun shaxs": "Шахси тамос",
  "Bajarilgan savdo": "Фурӯши иҷрошуда",
  "Barcha hududlar": "Ҳамаи ҳудудҳо",
  "Bu agent hech qanday mijoz, buyurtma yoki to'lovga bog'lanmagan. O'chirishni tasdiqlaysizmi?": "Ин агент ба ягон мизоҷ, фармоиш ё пардохт пайваст нест. Нест карданро тасдиқ мекунед?",
  "Bu agent mavjud emas yoki o'chirilgan.": "Ин агент мавҷуд нест ё нест шудааст.",
  "Bu mijoz uchun ma'lumot mavjud emas.": "Барои ин мизоҷ маълумот мавҷуд нест.",
  "Buyurtmalar soni": "Шумораи фармоишҳо",
  "Buyurtmalar yo'q": "Фармоишҳо нестанд",
  "Credit limit oshgan.": "Лимити қарз гузаштааст.",
  "CRM customer profile, agent assignment va kredit sozlamalari.": "Профили CRM, пайвасти агент ва танзими қарз.",
  "CRM mijozlar markazi: savdo, moliya va agentlarning real ma'lumotlari asosida.": "Маркази мизоҷони CRM бо маълумоти воқеии фурӯш, молия ва агентҳо.",
  "Faol agent": "Агенти фаъол",
  "Faol agent savdo va buyurtmalarda tanlanishi mumkin.": "Агенти фаъол дар фурӯш ва фармоишҳо интихоб мешавад.",
  "Faol emas qilish": "Ғайрифаъол кардан",
  "Faol mijoz": "Мизоҷи фаъол",
  "Faol qilish": "Фаъол кардан",
  "Faollashtirish": "Фаъол кардан",
  "Finance ulanganda bu qiymat derived balancega almashtiriladi.": "Пас аз пайвасти молия ин арзиш бо баланс иваз мешавад.",
  "Hudud ko'rsatilmagan": "Ҳудуд нишон дода нашудааст",
  "Ism, kompaniya, telefon, email...": "Ном, ширкат, телефон, email...",
  "Jami agent": "Ҳамагӣ агент",
  "Jami mijoz": "Ҳамагӣ мизоҷ",
  "Jami qarz": "Ҳамагӣ қарз",
  "Jami reja": "Ҳамагӣ нақша",
  "Jami to'langan": "Ҳамагӣ пардохтшуда",
  "Juda yaxshi": "Хеле хуб",
  "Keyingi aloqa muddati o'tgan.": "Муҳлати пайгирӣ гузаштааст.",
  "Keyingi aloqalar / izohlar": "Пайгириҳо / шарҳҳо",
  "Komissiya %": "Комиссия %",
  "Kontakt ma'lumotlari": "Маълумоти тамос",
  "Marshrut belgilanmagan": "Масир таъин нашудааст",
  "Masalan: Javohir Karimov": "Масалан: Ҷавоҳир Каримов",
  "Masalan: Yunusobod": "Масалан: Юнусобод",
  "Mijoz biriktirilmagan": "Мизоҷ пайваст нашудааст",
  "Mijoz CRM tafsiloti": "Тафсилоти CRM мизоҷ",
  "Mijoz nomi": "Номи мизоҷ",
  "Mijoz savdo tarixi mavjud emas.": "Таърихи фурӯши мизоҷ мавҷуд нест.",
  "Mijoz tahlili": "Таҳлили мизоҷ",
  "Mijoz tanlang": "Мизоҷро интихоб кунед",
  "Mijoz topilmadi": "Мизоҷ ёфт нашуд",
  "Mijoz turi": "Навъи мизоҷ",
  "Mijozlar mavjud emas.": "Мизоҷон мавҷуд нестанд.",
  "Mijozni tahrirlash": "Таҳрири мизоҷ",
  "Moliya moduli ulanmaguncha agent to'lovlari shu yerda paydo bo'ladi.": "То пайвасти модули молия, пардохтҳои агент ҳамин ҷо пайдо мешаванд.",
  "Moliya modulida mijoz to'lovi operatsiyasi yaratiladi.": "Дар модули молия амалиёти пардохти мизоҷ сохта мешавад.",
  "Moliya ulanganda tushum va qarzlar shu yerda real hisoblanadi.": "Пас аз пайвасти молия, воридот ва қарзҳо ҳамин ҷо ҳисоб мешаванд.",
  "Nomsiz agent": "Агенти беном",
  "o'chirilsinmi?": "нест карда шавад?",
  "O'chirish o'rniga faol emas qilindi.": "Ба ҷои нест кардан ғайрифаъол карда шуд.",
  "Oylik reja": "Нақшаи моҳона",
  "Oylik savdo rejasi": "Нақшаи моҳонаи фурӯш",
  "Pul / qarz xulosasi": "Хулосаи пул / қарз",
  "Qarz / kredit": "Қарз / кредит",
  "Qarz muddati xavfli.": "Муҳлати қарз хавфнок аст.",
  "Qarzdor mijozlar": "Мизоҷони қарздор",
  "Qolgan reja": "Нақшаи боқимонда",
  "Real savdo": "Фурӯши воқеӣ",
  "Reja %": "Нақша %",
  "Reja bajarilishi": "Иҷрои нақша",
  "Savdo agenti ma'lumotlarini kiriting.": "Маълумоти агенти фурӯшро ворид кунед.",
  "Savdo agentlari, hududlar, marshrutlar va rejalarni boshqarish.": "Идоракунии агентҳои фурӯш, ҳудудҳо, масирҳо ва нақшаҳо.",
  "Savdo moduli ulanmaguncha agent buyurtmalari shu yerda paydo bo'ladi.": "То пайвасти модули фурӯш, фармоишҳои агент ҳамин ҷо пайдо мешаванд.",
  "Sodiqlik / bonus": "Вафодорӣ / бонус",
  "STIR": "STIR",
  "ta buyurtma bog'langan": "адад фармоиш пайваст аст",
  "ta mijoz biriktirilgan": "адад мизоҷ пайваст аст",
  "ta moliya operatsiyasi mavjud": "адад амалиёти молия мавҷуд аст",
  "ta savdo mavjud": "адад фурӯш мавҷуд аст",
  "ta to'lov bog'langan": "адад пардохт пайваст аст",
  "Tahrirlamoqchi bo'lgan agent mavjud emas.": "Агенте, ки таҳрир мекунед, мавҷуд нест.",
  "Tahrirlash uchun customer mavjud emas.": "Барои таҳрир мизоҷ мавҷуд нест.",
  "tarix yo'q, to'liq o'chirish mumkin": "таърих нест, пурра нест кардан мумкин",
  "Taxminiy komissiya": "Комиссияи тахминӣ",
  "Teglar": "Тегҳо",
  "Telefon yo'q": "Телефон нест",
  "To'liq ism": "Ному насаб",
  "To'liq o'chirish bloklandi, agentni faol emas qilish tavsiya qilinadi.": "Несткунии пурра баста шуд, ғайрифаъол кардани агент тавсия мешавад.",
  "To'lov muddati (kun)": "Муҳлати пардохт (рӯз)",
  "To'lov tarixi mavjud emas.": "Таърихи пардохт мавҷуд нест.",
  "To'lovlar yo'q": "Пардохтҳо нестанд",
  "Topshirilgan pul": "Пули супоридашуда",
  "Tug'ilgan sana": "Санаи таваллуд",
  "Ushbu agentga hali mijoz biriktirilmagan.": "Ба ин агент ҳоло мизоҷ пайваст нашудааст.",
  "Vaqt chizig'i": "Хати вақт",
  "Vergul bilan ajrating": "Бо вергул ҷудо кунед",
  "Yangi agent": "Агенти нав",
  "Yangi eslatma / keyingi aloqa": "Ёддошти нав / пайгирӣ",
  "Yaxshi": "Хуб",
  "Yig'ilgan pul": "Пули ҷамъшуда",
  "Yunusobod - Chilonzor": "Юнусобод - Чилонзор",
  "Bog'lanmagan": "Пайваст нест",
  "Faqat o'qish uchun": "Танҳо барои дидан",
  "Keyingi aloqa izohi majburiy.": "Шарҳи пайгирӣ ҳатмист.",
  "Marshrut yo'q": "Масир нест",
  "Mijoz to'lovi": "Пардохти мизоҷ",
  "Tanlanmagan": "Интихоб нашудааст",
  "Do'kondan": "Аз мағоза",
  "Telegram": "Telegram",
  "Tavsiya": "Тавсия",
  "REGULAR": "Доимӣ",
  "NEW": "Нав",
  "RISK": "Хавфнок",
  "ACTIVE": "Фаъол",
  "INACTIVE": "Ғайрифаъол",
  "OPEN": "Кушода",
  "DONE": "Иҷро шуд",
  "CANCELLED": "Бекоршуда",
  "DRAFT": "Лоиҳа",
};
