export const productPurchaseTajikOverrides = {
  "1 partiyaga sarf": "Масраф барои 1 партия",
  "Asosiy ma'lumotlar": "Маълумоти асосӣ",
  "Asosiy yetkazib beruvchi": "Таъминкунандаи асосӣ",
  "Retsept / Recipe": "Ретсепт",
  "Backend ulangunga qadar demo retsept ma'lumotlari.": "То пайваст шудани сервер маълумоти намоишии ретсепт.",
  "Backend ulangunga qadar demo ishlab chiqarish buyurtmalari.": "То пайваст шудани сервер фармоишҳои намоишии истеҳсолӣ.",
  "Barcha xaridlar": "Ҳамаи харидҳо",
  "Barcha yetkazib beruvchilar": "Ҳамаи таъминкунандагон",
  "Barcode / QR": "Barcode / QR",
  "Barcode va boshqa identifikatorlar.": "Barcode ва идентификаторҳои дигар.",
  "Barcode": "Barcode",
  "Before / after": "Пеш / баъд",
  "Boshqa amallar": "Амалиётҳои дигар",
  "Brend": "Бренд",
  "Brend:": "Бренд:",
  "Bu buyurtma bo‘yicha omborga kirim amalga oshirilmaydi.": "Аз рӯи ин фармоиш ба анбор воридот иҷро намешавад.",
  "Bu mahsulot bo'yicha history hali yo'q.": "Барои ин маҳсулот ҳоло таърих нест.",
  "Bu mahsulot bo'yicha qoldiq tuzatish tarixi yo'q.": "Барои ин маҳсулот таърихи ислоҳи боқимонда нест.",
  "Bu mahsulot bo'yicha savdo mavjud emas.": "Барои ин маҳсулот фурӯш нест.",
  "Bu mahsulot bo'yicha xarid mavjud emas.": "Барои ин маҳсулот харид нест.",
  "Bu mahsulot mavjud emas yoki o'chirilgan.": "Ин маҳсулот нест ё нест карда шудааст.",
  "Bu xarid buyurtmasi mavjud emas yoki o‘chirilgan.": "Ин фармоиши харид нест ё нест карда шудааст.",
  "Buyurtma ma’lumotlari": "Маълумоти фармоиш",
  "Buyurtma sanasi": "Санаи фармоиш",
  "Buyurtma, supplier, ombor yoki mahsulot...": "Фармоиш, таъминкунанда, анбор ё маҳсулот...",
  "Buyurtma:": "Фармоиш:",
  "Buyurtmaning joriy holati.": "Ҳолати ҷории фармоиш.",
  "Chegirma (%)": "Тахфиф (%)",
  "Create, edit, status, stock, price, archive va restore eventlari.": "Ҳодисаҳои сохтан, таҳрир, ҳолат, захира, нарх, архив ва барқароркунӣ.",
  "Dona": "Дона",
  "Faol mahsulot savdo, ombor va ishlab chiqarish jarayonlarida ishlatilishi mumkin.": "Маҳсулоти фаъол дар фурӯш, анбор ва истеҳсолот истифода мешавад.",
  "Faqat qarzdor": "Танҳо қарздор",
  "Gram": "Грамм",
  "Hozir qabul": "Ҳозир қабул",
  "Hujjat": "Ҳуҷҷат",
  "Ichimliklar": "Нӯшокиҳо",
  "Identifikatsiya": "Идентификатсия",
  "Ishlab chiqarish ma'lumotlari": "Маълумоти истеҳсолот",
  "Jami buyurtmalar": "Ҳамаи фармоишҳо",
  "Jami xarid": "Ҳамагӣ харид",
  "Joriy qoldiq": "Боқимондаи ҷорӣ",
  "Kamida bitta mahsulot uchun qabul miqdorini kiriting.": "Барои ҳадди ақал як маҳсулот миқдори қабулро ворид кунед.",
  "Katalogga yangi xomashyo, tayyor mahsulot, savdo mahsuloti yoki xizmat qo'shish.": "Иловаи ашёи хом, маҳсулоти тайёр, маҳсулоти фурӯш ё хизмат ба каталог.",
  "Kategoriya tanlang": "Категорияро интихоб кунед",
  "Kechikayotgan": "Дер шуда истодааст",
  "Keyingi": "Баъдӣ",
  "Kilogram": "Килограмм",
  "Kutilayotgan sana": "Санаи интизорӣ",
  "Kutilayotgan": "Интизорӣ",
  "Litr": "Литр",
  "Mahsulot bo'yicha ichki izoh yoki muhim eslatmalar.": "Эзоҳи дохилӣ ё қайдҳои муҳим оид ба маҳсулот.",
  "Mahsulot bo'yicha ichki ma'lumot.": "Маълумоти дохилӣ оид ба маҳсулот.",
  "Mahsulot bo'yicha localStorage historydan olingan ombor o'zgarishlari.": "Тағйироти анбор аз таърихи браузер барои маҳсулот.",
  "Mahsulot faol": "Маҳсулот фаъол",
  "Mahsulot haqida qo'shimcha ma'lumot...": "Маълумоти иловагӣ дар бораи маҳсулот...",
  "Mahsulot nomi": "Номи маҳсулот",
  "Mahsulot qo‘shish": "Иловаи маҳсулот",
  "Mahsulot tarixi": "Таърихи маҳсулот",
  "Mahsulot turi": "Навъи маҳсулот",
  "Mahsulotlar mavjud emas.": "Маҳсулот нест.",
  "Mahsulotlarni qabul qilish": "Қабули маҳсулотҳо",
  "Mahsulotni ko'rish": "Дидани маҳсулот",
  "Mahsulotni o'chirish": "Нест кардани маҳсулот",
  "Mahsulotni tahrirlash": "Таҳрири маҳсулот",
  "Mahsulotni tezroq tanish uchun rasm qo'shishingiz mumkin.": "Барои зуд шинохтани маҳсулот метавонед расм илова кунед.",
  "Mahsulotning boshlang'ich va minimal qoldiq chegarasi.": "Боқимондаи аввалия ва ҳадди минималии маҳсулот.",
  "Mahsulotning katalog ma'lumotlari.": "Маълумоти каталоги маҳсулот.",
  "Mahsulotning moliyaviy parametrlari.": "Параметрҳои молиявии маҳсулот.",
  "Mahsulotning nomi, turi, kategoriya va identifikatsiyasi.": "Ном, навъ, категория ва идентификатсияи маҳсулот.",
  "Masalan: 4821": "Масалан: 4821",
  "Masalan: Un Premium": "Масалан: Орди Premium",
  "Masalan: Universal Foods": "Масалан: Universal Foods",
  "Masalan: inventarizatsiya natijasi...": "Масалан: натиҷаи инвентаризатсия...",
  "Masalan: yetkazib beruvchi narxi oshdi...": "Масалан: нархи таъминкунанда зиёд шуд...",
  "Material use": "Истифодаи мавод",
  "Mavjud stock": "Захираи мавҷуд",
  "Metr": "Метр",
  "Narx va soliq": "Нарх ва андоз",
  "Narxlar": "Нархҳо",
  "Narxni o'zgartirish": "Тағйири нарх",
  "Nomi, SKU yoki barcode bo'yicha qidirish...": "Ҷустуҷӯ аз рӯи ном, SKU ё barcode...",
  "Nomi": "Ном",
  "Nusxa olish": "Нусха гирифтан",
  "O'lchov birligi": "Воҳиди ченак",
  "Oldin qabul": "Қабули пешина",
  "Oxirgi ishlab chiqarish": "Истеҳсоли охирин",
  "Oxirgi tannarx": "Арзиши аслии охирин",
  "Oxirgi xarid:": "Хариди охирин:",
  "Pechenye": "Печенье",
  "QQS (%)": "ААИ (%)",
  "QR kod": "Коди QR",
  "Qabul qilingan yoki bekor qilingan xarid o‘zgartirilmaydi.": "Хариди қабулшуда ё бекоршуда тағйир дода намешавад.",
  "Qarz bor": "Қарз ҳаст",
  "Qaysi retseptda ishlatiladi": "Дар кадом ретсепт истифода мешавад",
  "Qo'shimcha ma'lumot": "Маълумоти иловагӣ",
  "Qo'shimchalar": "Иловаҳо",
  "Qoladi": "Мемонад",
  "Qoldiq harakatlari": "Амалиётҳои боқимонда",
  "Qoldiq holati": "Ҳолати боқимонда",
  "Qoldiqni tuzatish": "Ислоҳи боқимонда",
  "Qolgan qarz": "Қарзи боқимонда",
  "Rasm tanlash": "Интихоби расм",
  "Revenue": "Даромад",
  "Rezerv qilingan": "Резервшуда",
  "Sahifa": "Саҳифа",
  "Sales modulidagi real yakunlangan savdolar.": "Фурӯшҳои воқеии анҷомшуда аз модули фурӯш.",
  "Saqlanmagan qoralama": "Нусхаи сабтнашуда",
  "Sarlavha": "Сарлавҳа",
  "Savdo tarixi": "Таърихи фурӯш",
  "Savdo va xaridlar": "Фурӯш ва харидҳо",
  "Sotilgan miqdor": "Миқдори фурӯхташуда",
  "Sotuvlar soni": "Шумораи фурӯшҳо",
  "Status": "Ҳолат",
  "Tahrirlamoqchi bo'lgan mahsulot mavjud emas.": "Маҳсулоте, ки таҳрир кардан мехоҳед, нест.",
  "Tahrirlamoqchi bo‘lgan xarid mavjud emas.": "Хариде, ки таҳрир кардан мехоҳед, нест.",
  "Tannarx, sotuv narxi, QQS va chegirmani belgilang.": "Арзиши аслӣ, нархи фурӯш, ААИ ва тахфифро ворид кунед.",
  "Tarix": "Таърих",
  "Tavsif": "Тавсиф",
  "Tayyor yoki yarim tayyor mahsulot retsepti va ishlab chiqarish holati.": "Ретсепт ва ҳолати истеҳсолии маҳсулоти тайёр ё нимтайёр.",
  "To‘langan summa": "Маблағи пардохтшуда",
  "To‘langan va qarz summasi.": "Маблағи пардохтшуда ва қарз.",
  "To‘langan va qolgan qarz summasi.": "Маблағи пардохтшуда ва қарзи боқимонда.",
  "To‘langan": "Пардохтшуда",
  "To‘lov holati": "Ҳолати пардохт",
  "To‘lov jami summadan katta bo‘lishi mumkin emas.": "Пардохт аз маблағи умумӣ зиёд буда наметавонад.",
  "To‘lov manfiy bo‘lishi mumkin emas.": "Пардохт манфӣ буда наметавонад.",
  "To‘lov": "Пардохт",
  "To‘lovni yangilash": "Навсозии пардохт",
  "Turini tanlang": "Навъро интихоб кунед",
  "Umumiy xarid": "Хариди умумӣ",
  "Umumiy": "Умумӣ",
  "Xarid bekor qilingan": "Харид бекор шудааст",
  "Xarid bo‘yicha qo‘shimcha ma’lumot.": "Маълумоти иловагӣ оид ба харид.",
  "Xarid bo‘yicha qo‘shimcha ma’lumot...": "Маълумоти иловагӣ оид ба харид...",
  "Xarid buyurtmasi topilmadi.": "Фармоиши харид ёфт нашуд.",
  "Xarid ma’lumotlari": "Маълумоти харид",
  "Xarid narxi": "Нархи харид",
  "Xarid qabul qilingan": "Харид қабул шудааст",
  "Xarid qilinayotgan mahsulot yoki xomashyolar.": "Маҳсулот ё ашёи хоми харидшаванда.",
  "Xarid topilmadi": "Харид ёфт нашуд",
  "Xaridga qaytish": "Бозгашт ба харид",
  "Xaridlar tarixi": "Таърихи харидҳо",
  "Xaridlarga qaytish": "Бозгашт ба харидҳо",
  "Xaridni bekor qilish": "Бекор кардани харид",
  "Xaridni tahrirlab bo‘lmaydi": "Харидро таҳрир кардан мумкин нест",
  "Xaridni tahrirlash": "Таҳрири харид",
  "Xizmat": "Хизмат",
  "Xomashyo ishlatilishi": "Истифодаи ашёи хом",
  "Xomashyo va savdo mahsulotlari uchun demo xaridlar.": "Харидҳои намоишӣ барои ашёи хом ва маҳсулоти фурӯш.",
  "Xomashyo, yarim tayyor, tayyor va savdo mahsulotlarini boshqarish.": "Идораи ашёи хом, нимтайёр, тайёр ва маҳсулоти фурӯш.",
  "Yangi mahsulot": "Маҳсулоти нав",
  "Yangi qoldiq manfiy yoki noto'g'ri bo'lishi mumkin emas.": "Боқимондаи нав манфӣ ё нодуруст буда наметавонад.",
  "Yangi qoldiq": "Боқимондаи нав",
  "Yarim tayyor mahsulot": "Маҳсулоти нимтайёр",
  "Yetkazib beruvchi tanlang": "Таъминкунандаро интихоб кунед",
  "Yetkazib beruvchi va qabul qiluvchi ombor.": "Таъминкунанда ва анбори қабулкунанда.",
  "Yetkazib beruvchidan mahsulot yoki xomashyo xaridini yaratish.": "Сохтани хариди маҳсулот ё ашёи хом аз таъминкунанда.",
  "Yetkazib beruvchilardan mahsulot va xomashyo xaridlarini boshqarish.": "Идораи хариди маҳсулот ва ашёи хом аз таъминкунандагон.",
  "ombor qoldig‘iga qo‘shildi.": "ба боқимондаи анбор илова шуд.",
  "ta buyurtma": "фармоиш",
  "arxivsiz": "бе архив",
  "Arxivdan qaytarish": "Аз архив баргардонидан",
  "Arxivga o'tkazish": "Ба архив гузаронидан",
  "Qaytarish": "Баргардонидан",
  "Qidiruv yoki filterlarga mos xarid mavjud emas.": "Хариди мувофиқ ба ҷустуҷӯ ё филтрҳо нест.",
  "Hozircha xarid buyurtmalari mavjud emas.": "Ҳоло фармоиши харид нест.",
  "Marja:": "Маржа:",
  "Oldingi xarid qoralamasi mavjud. Oxirgi saqlangan vaqt:": "Қораламаи пешинаи харид мавҷуд аст. Вақти охирини сабт:",
  "Oldingi xarid qoralamasi mavjud.": "Қораламаи пешинаи харид мавҷуд аст.",
  "Qoralamani o‘chirish": "Нест кардани қоралама",
  "Sotuv narxi belgilanmagan": "Нархи фурӯш гузошта нашудааст",
  "arxivga o'tkaziladi.": "ба архив гузаронида мешавад.",
  "butunlay o'chiriladi. Bu amalni qaytarib bo'lmaydi.": "пурра нест карда мешавад. Ин амалро баргардонидан мумкин нест.",
  "faol holatga qaytariladi.": "ба ҳолати фаъол баргардонида мешавад.",
  "xarid buyurtmasi bekor qilinadi. Bu amal omborga kirim qilmaydi.": "фармоиши харид бекор карда мешавад. Ин амал ба анбор воридот намекунад.",
  "xarid buyurtmasi bekor qilinadi.": "фармоиши харид бекор карда мешавад."
};
