export const TABLE_REGISTRY = [
  {
    id: "products",
    label: "Mahsulotlar",
    columns: [
      { key: "product", title: "Mahsulot" },
      { key: "sku", title: "SKU" },
      { key: "type", title: "Turi" },
      { key: "category", title: "Kategoriya" },
      { key: "stock", title: "Qoldiq" },
      { key: "cost", title: "Tannarx" },
      { key: "salePrice", title: "Sotuv narxi" },
      { key: "margin", title: "Marja" },
      { key: "supplier", title: "Yetkazib beruvchi" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "customers",
    label: "Mijozlar",
    columns: [
      { key: "customer", title: "Mijoz" },
      { key: "phone", title: "Telefon" },
      { key: "agent", title: "Agent" },
      { key: "sales", title: "Savdo" },
      { key: "debt", title: "Qarz" },
      { key: "lastSale", title: "Oxirgi savdo" },
      { key: "segment", title: "Toifa" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "sales",
    label: "Savdo ro'yxati",
    columns: [
      { key: "number", title: "Sotuv" },
      { key: "customerName", title: "Mijoz" },
      { key: "agentName", title: "Agent" },
      { key: "warehouseName", title: "Ombor" },
      { key: "total", title: "Jami" },
      { key: "paidAmount", title: "To'langan" },
      { key: "debtAmount", title: "Qarz" },
      { key: "paymentStatus", title: "To'lov" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "purchases",
    label: "Xaridlar",
    columns: [
      { key: "number", title: "Buyurtma" },
      { key: "supplierName", title: "Yetkazib beruvchi" },
      { key: "warehouseName", title: "Ombor" },
      { key: "items", title: "Mahsulot" },
      { key: "total", title: "Jami" },
      { key: "paidAmount", title: "To'langan" },
      { key: "debtAmount", title: "Qarz" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "suppliers",
    label: "Yetkazib beruvchilar",
    columns: [
      { key: "name", title: "Yetkazib beruvchi" },
      { key: "contactPerson", title: "Aloqa shaxsi" },
      { key: "category", title: "Kategoriya" },
      { key: "purchases", title: "Xaridlar" },
      { key: "debt", title: "Qarz" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "agents",
    label: "Agentlar",
    columns: [
      { key: "name", title: "Agent" },
      { key: "region", title: "Hudud" },
      { key: "route", title: "Marshrut" },
      { key: "targetAmount", title: "Reja" },
      { key: "salesAmount", title: "Amaldagi savdo" },
      { key: "commissionPercent", title: "Komissiya" },
      { key: "customerIds", title: "Mijozlar" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "warehouse-stock",
    label: "Ombor qoldiqlari",
    columns: [
      { key: "product", title: "Mahsulot" },
      { key: "category", title: "Kategoriya" },
      { key: "quantity", title: "Jami qoldiq" },
      { key: "reserved", title: "Band qoldiq" },
      { key: "available", title: "Mavjud" },
      { key: "status", title: "Holat" },
      { key: "value", title: "Qiymati" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "production-orders",
    label: "Ishlab chiqarish buyurtmalari",
    columns: [
      { key: "number", title: "Buyurtma" },
      { key: "productName", title: "Mahsulot" },
      { key: "plannedQuantity", title: "Reja" },
      { key: "producedQuantity", title: "Ishlab chiqarildi" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "finance-transactions",
    label: "Moliya operatsiyalari",
    columns: [
      { key: "date", title: "Sana" },
      { key: "type", title: "Turi" },
      { key: "category", title: "Kategoriya" },
      { key: "source", title: "Manba" },
      { key: "counterparty", title: "Kontragent" },
      { key: "paymentMethod", title: "To'lov turi" },
      { key: "amount", title: "Summa" },
      { key: "cashboxName", title: "Kassa" },
      { key: "note", title: "Izoh" },
    ],
  },
  {
    id: "hr-employees",
    label: "Xodimlar jadvali",
    columns: [
      { key: "fullName", title: "Xodim" },
      { key: "position", title: "Lavozim" },
      { key: "department", title: "Bo'lim" },
      { key: "baseSalary", title: "Ish haqi" },
      { key: "today", title: "Bugungi holat" },
      { key: "shiftId", title: "Smena" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "payroll",
    label: "Oylik hisob-kitobi",
    columns: [
      { key: "employeeId", title: "Xodim" },
      { key: "baseAmount", title: "Asos" },
      { key: "bonuses", title: "Mukofot" },
      { key: "advances", title: "Avans" },
      { key: "penalties", title: "Jarima" },
      { key: "netAmount", title: "Sof oylik" },
      { key: "paidAmount", title: "To'langan" },
      { key: "debtAmount", title: "Qarz" },
      { key: "status", title: "Holat" },
      { key: "actions", title: "Amallar", locked: true },
    ],
  },
  {
    id: "reports-payroll",
    label: "Hisobot: oylik",
    columns: [
      { key: "employeeName", title: "Xodim" },
      { key: "baseAmount", title: "Asos" },
      { key: "bonuses", title: "Mukofot" },
      { key: "advances", title: "Avans" },
      { key: "penalties", title: "Jarima" },
      { key: "netAmount", title: "Sof oylik" },
      { key: "paidAmount", title: "To'langan" },
      { key: "debtAmount", title: "Qarz" },
    ],
  },
];

export const getTableDefinition = (tableId) =>
  TABLE_REGISTRY.find((table) => table.id === tableId);
